# Generated by Django 4.0.3 on 2022-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_marker_marker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='marker_type',
            field=models.IntegerField(choices=[(0, 'road'), (1, 'ambros')], default=0),
        ),
    ]
