# Generated by Django 4.0.3 on 2022-07-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_alter_marker_marker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
    ]
